# Site settings ################################################################
business_name: Ninesenses
title: Tom Skarbek-Wazynski
subtitle: Developer, Designer & Brand Consultant

# Contact ######################################################################
email: tom@ninesenses.co.uk
obfuscated_email: tom@ninesenses.co.uk

tel: +4407535644344
formated_tel: +44 [0] 7535 644 344

# twitter_username: wazynski
# instagram_username: wazynski

# Meta #########################################################################
description: >-
  Home of designer & full stack developer Tom Skarbek-Wazynski. Tom helps companies look their best and make their products exceptional to use.

keywords: >-
  Ninesenses, Tom Skarbek-Wazynski, web design, website design, web development, branding,
  digital marketing, online marketing, email marketing

author: "copyright ©2017 : ninesenses : http://ninesenses.co.uk : tom@ninesenses.co.uk"

# Collections ##################################################################
collections:
  projects:
    output: true
    permalink: /case-studies/:name

# Open Graph settings ##########################################################
og_title: Home
og_type: website
og_description: >-
  Ninesenses is an independent creative consultancy producing high
  quality bespoke websites and digital products for ...
og_image: http://ninesenses.co.uk/img/og.png
og_image_width: 200
og_image_height: 200

# Footer #######################################################################
colphon: Typeset in Sofia Pro
copyright: All rights reserved <span>© Tom Skarbek-Wazynski</span>

# Typekit ID ###################################################################
typekit: fte0rot

# URL ##########################################################################
baseurl: ""
url: "https://ninesenses.co.uk"

# Build ########################################################################
env: production

plugins:
  - jekyll-babel

# Server Config options
livereload: true # You no longer need to include --livereload

exclude:
  [
    vendor,
    _assets,
    gulpfile.js,
    README.md,
    node_modules,
    yarn.lock,
    package.json,
  ]
